"use client"
import './globals.scss'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { useState } from 'react'

import {
  Button,
  Header,
  HeaderName,
  HeaderMenuButton,
  HeaderSideNavItems,
  HeaderMenuItem,
  HeaderMenu,
  SideNav,
  SideNavItems,
  SideNavMenuItem,
  HeaderGlobalBar,
  HeaderGlobalAction,
  SideNavLink,
  Theme,
  GlobalTheme
} from "@carbon/react";
import { Search,  Notification, UserAvatar, Fade } from '@carbon/icons-react';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: any) {

  const [isSidebar, setIsSidebar] = useState(false)
  const toggleSidebar = () => {
    setIsSidebar(!isSidebar)
  }
  const action = (message: string) => {
    console.log(message);
  }
  return (
    <html>
      <body>
        <Theme theme="g90" >
          <Header aria-label="Coles Platform Name">
          <HeaderMenuButton 
              aria-label={isSidebar ? 'Close menu' : 'Open menu'} 
              onClick={toggleSidebar} 
              isActive={isSidebar} 
              aria-expanded={isSidebar} />
              <HeaderGlobalBar>
            <HeaderGlobalAction aria-label="Search" onClick={action('search click')}>
              <Search size={20} />
            </HeaderGlobalAction>
            <HeaderGlobalAction aria-label="Notifications" onClick={action('notification click')}>
              <Notification size={20} />
            </HeaderGlobalAction>
            <HeaderGlobalAction aria-label="App Switcher" onClick={action('app-switcher click')} tooltipAlignment="end">
              <UserAvatar size={20} />
            </HeaderGlobalAction>
          </HeaderGlobalBar>
            <SideNav aria-label="Side navigation" 
                expanded={isSidebar} 
                isPersistent={false} 
                onSideNavBlur={toggleSidebar}>
                <SideNavItems>
                    <SideNavLink href="/dashboard">Dashboard!</SideNavLink>
                    <SideNavLink href="/dashboard">Dashboard</SideNavLink>
                    <SideNavLink href="/dashboard">Dashboard</SideNavLink>
                    <SideNavLink href="/dashboard">Dashboard</SideNavLink>
                    <SideNavLink href="/dashboard">Dashboard</SideNavLink>
                    <SideNavLink href="/dashboard">Dashboard</SideNavLink>
                </SideNavItems>
              </SideNav>
          </Header>
        </Theme>
          <main>{children}</main>
      </body>
    </html>
  )
}
